apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-notes-app
  labels:
    apps: django-label
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: django-label
  template:
      metadata:
        name: django-pod
        labels:
          apps: django-label
      spec:
        containers:
          - name: django-notes-container:10
            image: asadkhan03/notes-app
            ports:
              - containerPort: 8000
